### ISSUE TITLE
Typescript 5 @InjectModel raises: Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.ts

### ISSUE THREAD

**Issue by msimon** [nestjs/sequelize#1237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

With typescript 5, Any `@InjectModel` has the following error attached to it:
> Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.ts(1239)

 "@nestjs/sequelize": "^9.0.0" > sequelize.decorators.d.ts still has the following:
```
export declare const InjectModel: (entity: Function, connection?: string) => (target: object, key: string | symbol, index?: number | undefined) => void;
```

I may need to be re-compiled using the latest nestjs/common and re-deploy to npm, to get this bugfix in: https://github.com/nestjs/nest/pull/10970

### Minimum reproduction code

N/a

### Steps to reproduce

N/A

### Expected behavior

No error

### Package version

9.0.0

### NestJS version

9.3.12

### Node.js version

16.14

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Update @nestjs/common to the latest version
