### ISSUE TITLE
Need to rebuild & republish to npm to get type from nestjs/common. Typescript 5 @InjectModel raises: Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.ts

### ISSUE THREAD

**Issue by msimon** [nestjs/sequelize#1239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Re-opening this issue as the previous one got closed and locked: https://github.com/nestjs/sequelize/issues/1237

The problem is not that my nestjs/common is outdated locally, is that the code in the nestjs/sequelize in npm was not built against the new nest/common. Hence the type inference for the injectModel function is based on the previous version of common, and therefore does not have the added `| undefined` required.

Looking at the code here: https://www.npmjs.com/package/@nestjs/sequelize?activeTab=code
![@nestjs:sequelize - npm 2023-04-04 14-03-20](https://user-images.githubusercontent.com/321204/229800730-1b8a312c-59d6-42e4-a5b7-2256b969711f.png)

- The file /@nestjs/sequelize/dist/common/sequelize.decorators.d.ts is missing the undefined
- If I download the nest/squelize github project and build, the `sequelize.decorators.d.ts` is properly inferred against the last nestjs/common
- The project needs to be rebuilt and published to npm again.

### Minimum reproduction code

N/a

### Steps to reproduce

N/A

### Expected behavior

N/A

### Package version

9.0.0

### NestJS version

9.3.12

### Node.js version

16.14

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

My nestJs common is at `9.3.12` (latest version to date)

**Comment by kamilmysliwiec** [comment]
Great catch! Thank you @msimon 

Fixed in 9.0.1
