### ISSUE TITLE
sequelize 7 support

### ISSUE THREAD

**Issue by yuntian001** [nestjs/sequelize#1346]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

A preview version of sequelize 7 has been released, Official support for typescript requires no third-party packages and applies to transaction usage [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage)  Did very friendly support . Can you provide the corresponding preview version

### Describe the solution you'd like

An alpha version is available supporting sequelize v7

### Teachability, documentation, adoption, migration strategy

https://sequelize.org/docs/v7/

### What is the motivation / use case for changing the behavior?

A preview version of sequelize 7 has been released, Official support for typescript requires no third-party packages and applies to transaction usage [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage)  Did very friendly support

**Comment by kamilmysliwiec** [comment]
We will, as soon as it becomes stable. We won't support an alpha version.
