### ISSUE TITLE
Switch to sequelize v7

### ISSUE THREAD

**Issue by rcronin** [nestjs/sequelize#1391]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently this package uses sequelize-typescript. I’d like to see this upgraded to utilize sequelize v7

### Describe the solution you'd like

Swap integration to sequelize/core trading v7, which contains all the native typescript typings, etc

### Teachability, documentation, adoption, migration strategy

Possibly version this in a way so people utilizing sequelize typescript don’t have to upgrade until ready

### What is the motivation / use case for changing the behavior?

Motivation to use this is just keep things current with latest version of sequelize

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/sequelize/issues/1346
