### ISSUE TITLE
Unresolved npm dependencies with nestjs 10.3.2

### ISSUE THREAD

**Issue by mannes-paqt** [nestjs/sequelize#1426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I follow instructions to add this library to a nest application i get the following error from npm

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sequelize-test@0.0.1
npm ERR! Found: reflect-metadata@0.2.1
npm ERR! node_modules/reflect-metadata
npm ERR!   reflect-metadata@"^0.2.0" from the root project
npm ERR!   peer reflect-metadata@"^0.1.12 || ^0.2.0" from @nestjs/common@10.3.2
npm ERR!   node_modules/@nestjs/common
npm ERR!     @nestjs/common@"^10.0.0" from the root project
npm ERR!     peer @nestjs/common@"^8.0.0 || ^9.0.0 || ^10.0.0" from @nestjs/sequelize@10.0.0
npm ERR!     node_modules/@nestjs/sequelize
npm ERR!       @nestjs/sequelize@"*" from the root project
npm ERR!     5 more (@nestjs/core, @nestjs/microservices, ...)
npm ERR!   3 more (@nestjs/core, @nestjs/microservices, @nestjs/websockets)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer reflect-metadata@"^0.1.13" from @nestjs/sequelize@10.0.0
npm ERR! node_modules/@nestjs/sequelize
npm ERR!   @nestjs/sequelize@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Minimum reproduction code

no code created

### Steps to reproduce

1. create new application with nest-cli, `nest new sequelize-test`
3. run `npm i --save @nestjs/sequelize sequelize-typescript sequelize` in new project dir

### Expected behavior

Should install sequelize and dependencies without error

### Package version

latest (10.0.0?)

### NestJS version

10.3.2

### Node.js version

v18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by abhinav-novo** [comment]
@mannes-paqt Downgrading the "reflect-metadata" version in your package.json file might resolve this issue.
```
    "reflect-metadata": "^0.1.13",
```

I am also facing the same issue and it needs to be fixed by the maintainers for this repository as they have fixed the peerDependcies like below. [[Refer](https://github.com/nestjs/sequelize/blob/master/package.json)]

```
  "peerDependencies": {
    "@nestjs/common": "^8.0.0 || ^9.0.0 || ^10.0.0",
    "@nestjs/core": "^8.0.0 || ^9.0.0 || ^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "sequelize": "^6.3.5",
    "sequelize-typescript": "^2.0.0"
  },
```

**Comment by ab14bhardwaj** [comment]
@mannes-paqt  Downgrading the "reflect-metadata" version in your package.json file might resolve this issue.
```
   "reflect-metadata": "^0.1.13",
```

I am also facing the same issue and it needs to be fixed by the maintainers for this repository as they have fixed the peerDependcies like below. [[Refer](https://github.com/nestjs/sequelize/blob/master/package.json)]

```
  "peerDependencies": {
    "@nestjs/common": "^8.0.0 || ^9.0.0 || ^10.0.0",
    "@nestjs/core": "^8.0.0 || ^9.0.0 || ^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "sequelize": "^6.3.5",
    "sequelize-typescript": "^2.0.0"
  },
```

**Comment by Tony133** [comment]
There is a PR that solves this problem here: https://github.com/nestjs/sequelize/pull/1415

**Comment by fire015** [comment]
+1 issue

**Comment by kamilmysliwiec** [comment]
Fixed
