### ISSUE TITLE
InjectModel error

### ISSUE THREAD

**Issue by buzai** [nestjs/sequelize#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

[Nest] 66813  - 2024/11/21 11:41:10     LOG [NestFactory] Starting Nest application...
[Nest] 66813  - 2024/11/21 11:41:10     LOG [InstanceLoader] SequelizeModule dependencies initialized +68ms
[Nest] 66813  - 2024/11/21 11:41:10     LOG [InstanceLoader] SequelizeModule dependencies initialized +0ms
[Nest] 66813  - 2024/11/21 11:41:10     LOG [InstanceLoader] SequelizeCoreModule dependencies initialized +0ms
[Nest] 66813  - 2024/11/21 11:41:10   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AppService (destConnection, ?). Please make sure that the argument "dest_UserModelRepository" at index [1] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If "dest_UserModelRepository" is a provider, is it part of the current AppModule?
- If "dest_UserModelRepository" is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing "dest_UserModelRepository" */ ]
  })

Error: Nest can't resolve dependencies of the AppService (destConnection, ?). Please make sure that the argument "dest_UserModelRepository" at index [1] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If "dest_UserModelRepository" is a provider, is it part of the current AppModule?
- If "dest_UserModelRepository" is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing "dest_UserModelRepository" */ ]
  })

    at Injector.lookupComponentInParentModules (~./demo-error/node_modules/@nestjs/core/injector/injector.js:255:19)
    at async Injector.resolveComponentInstance (~./demo-error/node_modules/@nestjs/core/injector/injector.js:208:33)
    at async resolveParam (~./demo-error/node_modules/@nestjs/core/injector/injector.js:129:38)
    at async Promise.all (index 1)
    at async Injector.resolveConstructorParams (~./demo-error/node_modules/@nestjs/core/injector/injector.js:144:27)
    at async Injector.loadInstance (~./demo-error/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (~./demo-error/node_modules/@nestjs/core/injector/injector.js:98:9)
    at async ~./demo-error/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (~./demo-error/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
^C

### Minimum reproduction code

https://github.com/buzai/demo-error

### Steps to reproduce

1 npm install
2 cp .env .env.example
3 edit the .env for mysql
4 npm run start:dev
5 it will throw a error 

### Expected behavior

no error when load the model, or how to get the model from descSequelize (Sequelize instance)?

### Package version

10.0.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
