### ISSUE TITLE
@gperdomor there are a few minor breaking changes. You can find the migration guide & instructions on the `8.0.0` branch of the docs https://github.com/nestjs/docs.nestjs.com/tree/8.0.0

### ISSUE THREAD

**Issue by paulocheloni** [nestjs/sequelize#896]
@gperdomor there are a few minor breaking changes. You can find the migration guide & instructions on the `8.0.0` branch of the docs https://github.com/nestjs/docs.nestjs.com/tree/8.0.0

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/6349#issuecomment-847647336_

This link is not available anymore where can I find those references?

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/migration-guide
